/**
 * Complaint Generator Page – NyayaSetu
 * Smart form that generates a formatted legal complaint letter
 * and provides a PDF download option.
 */
import { useState } from "react";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { zodResolver } from "@hookform/resolvers/zod";
import { Download, FileText, CheckCircle, AlertCircle } from "lucide-react";
import jsPDF from "jspdf";

// ── Validation schema ──
const complaintSchema = z.object({
  fullName: z.string().trim().min(2, "Name must be at least 2 characters").max(100),
  address: z.string().trim().min(10, "Please enter a complete address").max(300),
  phone: z
    .string()
    .trim()
    .regex(/^[6-9]\d{9}$/, "Enter a valid 10-digit Indian mobile number"),
  email: z.string().trim().email("Enter a valid email address").optional().or(z.literal("")),
  complaintType: z.string().min(1, "Please select a complaint type"),
  incidentDate: z.string().min(1, "Please select the incident date"),
  incidentPlace: z.string().trim().min(3, "Please specify the place").max(200),
  description: z
    .string()
    .trim()
    .min(50, "Description must be at least 50 characters")
    .max(2000, "Description must be under 2000 characters"),
  authorityName: z.string().trim().min(2, "Please name the authority").max(200),
});

type ComplaintForm = z.infer<typeof complaintSchema>;

const complaintTypes = [
  "Police Complaint (FIR)",
  "Consumer Complaint",
  "Cyber Crime / Online Fraud",
  "Tenant-Landlord Dispute",
  "RTI Application",
  "Workplace Harassment",
  "Public Grievance",
  "Other",
];

const ComplaintGenerator = () => {
  const [generated, setGenerated] = useState(false);
  const [letterContent, setLetterContent] = useState("");

  const {
    register,
    handleSubmit,
    watch,
    formState: { errors, isSubmitting },
  } = useForm<ComplaintForm>({
    resolver: zodResolver(complaintSchema),
    defaultValues: { complaintType: "", email: "" },
  });

  const description = watch("description", "");

  // ── Generate letter text ──
  const buildLetter = (data: ComplaintForm): string => {
    const today = new Date().toLocaleDateString("en-IN", {
      day: "numeric",
      month: "long",
      year: "numeric",
    });

    return `To,
${data.authorityName}

Subject: Complaint Regarding ${data.complaintType}

Respected Sir/Madam,

I, ${data.fullName}, residing at ${data.address}, Phone: ${data.phone}${data.email ? `, Email: ${data.email}` : ""}, hereby submit this formal complaint for your kind attention and necessary action.

NATURE OF COMPLAINT: ${data.complaintType}

DETAILS OF INCIDENT:

Date of Incident: ${data.incidentDate}
Place of Incident: ${data.incidentPlace}

DESCRIPTION OF INCIDENT:

${data.description}

In view of the above, I kindly request your good office to:
1. Take immediate cognizance of this complaint.
2. Register this complaint and provide an acknowledgement receipt.
3. Initiate appropriate inquiry and take necessary legal action.
4. Keep me informed of the progress at the address/contact mentioned above.

I assure you that all the information provided in this complaint is true and correct to the best of my knowledge.

Yours sincerely,

${data.fullName}
${data.address}
Phone: ${data.phone}${data.email ? `\nEmail: ${data.email}` : ""}

Date: ${today}

---
Generated by NyayaSetu – Legal Help Simplifier`;
  };

  // ── Generate PDF ──
  const downloadPDF = () => {
    const doc = new jsPDF({ unit: "mm", format: "a4" });
    const margin = 20;
    const pageWidth = 210;
    const usableWidth = pageWidth - 2 * margin;
    let y = 20;

    // Header
    doc.setFillColor(26, 78, 153);
    doc.rect(0, 0, 210, 30, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");
    doc.text("NyayaSetu – Legal Help Simplifier", margin, 14);
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text("Formal Complaint Letter", margin, 22);
    y = 42;

    // Body text
    doc.setTextColor(20, 30, 50);
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");

    const lines = doc.splitTextToSize(letterContent, usableWidth);
    lines.forEach((line: string) => {
      if (y > 275) {
        doc.addPage();
        y = 20;
      }
      doc.text(line, margin, y);
      y += 5.5;
    });

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(120, 130, 150);
    doc.text(
      `Generated on ${new Date().toLocaleDateString("en-IN")} | NyayaSetu – nyayasetu.in`,
      margin,
      290
    );

    doc.save(`Complaint_${Date.now()}.pdf`);
  };

  // ── On Submit ──
  const onSubmit = (data: ComplaintForm) => {
    const letter = buildLetter(data);
    setLetterContent(letter);
    setGenerated(true);
    window.scrollTo({ top: 0, behavior: "smooth" });
  };

  return (
    <div className="max-w-5xl mx-auto px-4 py-10">
      <div className="text-center mb-10">
        <h1 className="text-3xl md:text-4xl font-bold text-foreground mb-3">
          Smart Complaint Generator
        </h1>
        <div className="section-divider" />
        <p className="text-muted-foreground mt-4 max-w-xl mx-auto">
          Fill in the details below. We'll generate a professional complaint letter you can download as PDF.
        </p>
      </div>

      {/* ── Success Banner ── */}
      {generated && (
        <div className="mb-8 bg-success/10 border border-success/30 rounded-2xl p-5 flex items-start gap-4">
          <CheckCircle className="w-6 h-6 text-success mt-0.5 flex-shrink-0" />
          <div>
            <p className="font-semibold text-success mb-1">Complaint letter generated successfully! ✅</p>
            <p className="text-sm text-muted-foreground">
              Review your letter below and download the PDF to submit it to the relevant authority.
            </p>
          </div>
        </div>
      )}

      <div className="grid md:grid-cols-2 gap-8">
        {/* ── Form ── */}
        <div>
          <div className="bg-card rounded-2xl border border-border p-6">
            <h2 className="font-bold text-foreground text-lg mb-5 flex items-center gap-2">
              <FileText className="w-5 h-5 text-primary" />
              Complaint Details
            </h2>

            <form onSubmit={handleSubmit(onSubmit)} className="space-y-4">
              {/* Full Name */}
              <div>
                <label className="block text-sm font-medium text-foreground mb-1">
                  Full Name <span className="text-destructive">*</span>
                </label>
                <input
                  {...register("fullName")}
                  placeholder="e.g. Rahul Kumar Sharma"
                  className="w-full px-3 py-2.5 rounded-lg border border-input bg-background text-sm focus:outline-none focus:ring-2 focus:ring-ring transition"
                />
                {errors.fullName && <p className="text-destructive text-xs mt-1 flex items-center gap-1"><AlertCircle className="w-3 h-3" />{errors.fullName.message}</p>}
              </div>

              {/* Address */}
              <div>
                <label className="block text-sm font-medium text-foreground mb-1">
                  Address <span className="text-destructive">*</span>
                </label>
                <textarea
                  {...register("address")}
                  placeholder="House No., Street, City, State, PIN"
                  rows={2}
                  className="w-full px-3 py-2.5 rounded-lg border border-input bg-background text-sm resize-none focus:outline-none focus:ring-2 focus:ring-ring transition"
                />
                {errors.address && <p className="text-destructive text-xs mt-1 flex items-center gap-1"><AlertCircle className="w-3 h-3" />{errors.address.message}</p>}
              </div>

              {/* Phone + Email row */}
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block text-sm font-medium text-foreground mb-1">
                    Phone No. <span className="text-destructive">*</span>
                  </label>
                  <input
                    {...register("phone")}
                    placeholder="10-digit number"
                    maxLength={10}
                    className="w-full px-3 py-2.5 rounded-lg border border-input bg-background text-sm focus:outline-none focus:ring-2 focus:ring-ring transition"
                  />
                  {errors.phone && <p className="text-destructive text-xs mt-1">{errors.phone.message}</p>}
                </div>
                <div>
                  <label className="block text-sm font-medium text-foreground mb-1">Email (optional)</label>
                  <input
                    {...register("email")}
                    type="email"
                    placeholder="your@email.com"
                    className="w-full px-3 py-2.5 rounded-lg border border-input bg-background text-sm focus:outline-none focus:ring-2 focus:ring-ring transition"
                  />
                  {errors.email && <p className="text-destructive text-xs mt-1">{errors.email.message}</p>}
                </div>
              </div>

              {/* Complaint Type */}
              <div>
                <label className="block text-sm font-medium text-foreground mb-1">
                  Complaint Type <span className="text-destructive">*</span>
                </label>
                <select
                  {...register("complaintType")}
                  className="w-full px-3 py-2.5 rounded-lg border border-input bg-background text-sm focus:outline-none focus:ring-2 focus:ring-ring transition"
                >
                  <option value="">-- Select Type --</option>
                  {complaintTypes.map((t) => (
                    <option key={t} value={t}>{t}</option>
                  ))}
                </select>
                {errors.complaintType && <p className="text-destructive text-xs mt-1 flex items-center gap-1"><AlertCircle className="w-3 h-3" />{errors.complaintType.message}</p>}
              </div>

              {/* Authority */}
              <div>
                <label className="block text-sm font-medium text-foreground mb-1">
                  To (Authority Name) <span className="text-destructive">*</span>
                </label>
                <input
                  {...register("authorityName")}
                  placeholder="e.g. The Station House Officer, XYZ Police Station"
                  className="w-full px-3 py-2.5 rounded-lg border border-input bg-background text-sm focus:outline-none focus:ring-2 focus:ring-ring transition"
                />
                {errors.authorityName && <p className="text-destructive text-xs mt-1 flex items-center gap-1"><AlertCircle className="w-3 h-3" />{errors.authorityName.message}</p>}
              </div>

              {/* Incident Date + Place */}
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block text-sm font-medium text-foreground mb-1">
                    Incident Date <span className="text-destructive">*</span>
                  </label>
                  <input
                    type="date"
                    {...register("incidentDate")}
                    max={new Date().toISOString().split("T")[0]}
                    className="w-full px-3 py-2.5 rounded-lg border border-input bg-background text-sm focus:outline-none focus:ring-2 focus:ring-ring transition"
                  />
                  {errors.incidentDate && <p className="text-destructive text-xs mt-1">{errors.incidentDate.message}</p>}
                </div>
                <div>
                  <label className="block text-sm font-medium text-foreground mb-1">
                    Place of Incident <span className="text-destructive">*</span>
                  </label>
                  <input
                    {...register("incidentPlace")}
                    placeholder="e.g. Sector 15, Gurgaon"
                    className="w-full px-3 py-2.5 rounded-lg border border-input bg-background text-sm focus:outline-none focus:ring-2 focus:ring-ring transition"
                  />
                  {errors.incidentPlace && <p className="text-destructive text-xs mt-1">{errors.incidentPlace.message}</p>}
                </div>
              </div>

              {/* Description */}
              <div>
                <label className="block text-sm font-medium text-foreground mb-1">
                  Incident Description <span className="text-destructive">*</span>
                </label>
                <textarea
                  {...register("description")}
                  placeholder="Describe the incident in detail — what happened, who was involved, what you lost or suffered..."
                  rows={5}
                  className="w-full px-3 py-2.5 rounded-lg border border-input bg-background text-sm resize-none focus:outline-none focus:ring-2 focus:ring-ring transition"
                />
                <div className="flex justify-between items-center mt-1">
                  {errors.description
                    ? <p className="text-destructive text-xs flex items-center gap-1"><AlertCircle className="w-3 h-3" />{errors.description.message}</p>
                    : <p className="text-xs text-muted-foreground">Minimum 50 characters</p>
                  }
                  <span className={`text-xs ${description.length > 1900 ? "text-destructive" : "text-muted-foreground"}`}>
                    {description.length}/2000
                  </span>
                </div>
              </div>

              <button
                type="submit"
                disabled={isSubmitting}
                className="w-full py-3 rounded-xl hero-gradient text-primary-foreground font-semibold shadow-[var(--shadow-button)] hover:opacity-90 disabled:opacity-50 transition"
              >
                {isSubmitting ? "Generating..." : "📄 Generate Complaint Letter"}
              </button>
            </form>
          </div>
        </div>

        {/* ── Letter Preview ── */}
        <div>
          <div className="bg-card rounded-2xl border border-border p-6 sticky top-24">
            <div className="flex items-center justify-between mb-4">
              <h2 className="font-bold text-foreground flex items-center gap-2">
                <FileText className="w-5 h-5 text-primary" />
                Letter Preview
              </h2>
              {generated && (
                <button
                  onClick={downloadPDF}
                  className="flex items-center gap-1.5 px-4 py-2 rounded-lg hero-gradient text-primary-foreground text-sm font-medium shadow hover:opacity-90 transition"
                >
                  <Download className="w-4 h-4" />
                  Download PDF
                </button>
              )}
            </div>

            {generated ? (
              <pre className="text-xs text-muted-foreground whitespace-pre-wrap leading-relaxed bg-background rounded-xl border border-border p-4 max-h-[500px] overflow-y-auto font-mono">
                {letterContent}
              </pre>
            ) : (
              <div className="flex flex-col items-center justify-center h-64 text-center text-muted-foreground">
                <FileText className="w-12 h-12 mb-4 opacity-20" />
                <p className="text-sm">Fill in the form and click</p>
                <p className="text-sm font-medium">"Generate Complaint Letter"</p>
                <p className="text-xs mt-2 opacity-70">Your formatted letter will appear here.</p>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};

export default ComplaintGenerator;
